config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

mount Sidekiq::Web, at: '/sidekiq'

  resources :query_results

  resources :queries
  match 'get_query', to: 'queries#add_or_update', via: [:post]

  resources :campaigns

  devise_scope :user do
    authenticated :user do
      root 'dashboard#show', as: :authenticated_root
    end
    unauthenticated :user do
      root 'home#show', as: :unauthenticated_root
    end
  end

    devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
    resources :domains

    resources :campaings

    resources :search_engines

    match 'get_campaigns/:domain_id' => 'ajax_json#get_campaigns',  via: :get

  end

app/models/query_result.rb
class QueryResult < ActiveRecord::Base
  belongs_to :query

  def self.insert_or_update_data(result)
    result.each do |query_id, value|
      if query_result = self.find_by(query_id: query_id)
        query_result.update_attributes(previous_position: query_result.position, last_updated: query_result.updated_at, position: value["position"], url: value["url"])
      else
        self.create(query_id: query_id, position: value["position"], url: value["url"], last_updated: Time.now)
      end
    end
  end
end

app/controllers/query_results_controller.rb
class QueryResultsController < ApplicationController
  before_action :set_query_result, only: [:show, :edit, :update, :destroy]

  # GET /query_results
  # GET /query_results.json
  def index
    @query_results = QueryResult.all
  end

  # GET /query_results/1
  # GET /query_results/1.json
  def show
  end

  # GET /query_results/new
  def new
    @query_result = QueryResult.new
  end

  # GET /query_results/1/edit
  def edit
  end

  # POST /query_results
  # POST /query_results.json
  def create
    @query_result = QueryResult.new(query_result_params)

    respond_to do |format|
      if @query_result.save
        format.html { redirect_to @query_result, notice: 'Query result was successfully created.' }
        format.json { render :show, status: :created, location: @query_result }
      else
        format.html { render :new }
        format.json { render json: @query_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /query_results/1
  # PATCH/PUT /query_results/1.json
  def update
    respond_to do |format|
      if @query_result.update(query_result_params)
        format.html { redirect_to @query_result, notice: 'Query result was successfully updated.' }
        format.json { render :show, status: :ok, location: @query_result }
      else
        format.html { render :edit }
        format.json { render json: @query_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /query_results/1
  # DELETE /query_results/1.json
  def destroy
    @query_result.destroy
    respond_to do |format|
      format.html { redirect_to query_results_url, notice: 'Query result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_query_result
      @query_result = QueryResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def query_result_params
      params.require(:query_result).permit(:query_id, :position, :previous_position, :last_updated)
    end
end

app/helpers/query_results_helper.rb
module QueryResultsHelper
end

app/views/query_results/_form.html.erb
<%= form_for(@query_result) do |f| %>
  <% if @query_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@query_result.errors.count, "error") %> prohibited this query_result from being saved:</h2>

      <ul>
      <% @query_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query_id %><br>
    <%= f.text_field :query_id %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :previous_position %><br>
    <%= f.number_field :previous_position %>
  </div>
  <div class="field">
    <%= f.label :last_updated %><br>
    <%= f.datetime_select :last_updated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/query_results/edit.html.erb
<h1>Editing query_result</h1>

<%= render 'form' %>

<%= link_to 'Show', @query_result %> |
<%= link_to 'Back', query_results_path %>

app/views/query_results/index.html.erb
<h1>Listing query_results</h1>

<table>
  <thead>
    <tr>
      <th>Query</th>
      <th>Position</th>
      <th>Previous position</th>
      <th>Last updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @query_results.each do |query_result| %>
      <tr>
        <td><%= query_result.query %></td>
        <td><%= query_result.position %></td>
        <td><%= query_result.previous_position %></td>
        <td><%= query_result.last_updated %></td>
        <td><%= link_to 'Show', query_result %></td>
        <td><%= link_to 'Edit', edit_query_result_path(query_result) %></td>
        <td><%= link_to 'Destroy', query_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Query result', new_query_result_path %>

app/views/query_results/new.html.erb
<h1>New query_result</h1>

<%= render 'form' %>

<%= link_to 'Back', query_results_path %>

app/views/query_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Query:</strong>
  <%= @query_result.query %>
</p>

<p>
  <strong>Position:</strong>
  <%= @query_result.position %>
</p>

<p>
  <strong>Previous position:</strong>
  <%= @query_result.previous_position %>
</p>

<p>
  <strong>Last updated:</strong>
  <%= @query_result.last_updated %>
</p>

<%= link_to 'Edit', edit_query_result_path(@query_result) %> |
<%= link_to 'Back', query_results_path %>