config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

mount Sidekiq::Web, at: '/sidekiq'

  resources :query_results

  resources :queries
  match 'get_query', to: 'queries#add_or_update', via: [:post]

  resources :campaigns

  devise_scope :user do
    authenticated :user do
      root 'dashboard#show', as: :authenticated_root
    end
    unauthenticated :user do
      root 'home#show', as: :unauthenticated_root
    end
  end

    devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
    resources :domains

    resources :campaings

    resources :search_engines

    match 'get_campaigns/:domain_id' => 'ajax_json#get_campaigns',  via: :get

  end

app/models/query.rb
class Query < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :search_engine
  has_one :query_result
  validates :keyword, :uniqueness => {scope: [:campaign_id, :search_engine_id]}, presence: true

  def self.to_csv(options={})
    CSV.generate(options) do |csv|
      csv << ["Domain", "Campaign",  "Keyword", "Engine", "Position", "Ranking page Url", "Previous Positon", "Last Updated"]
      all.each do |query|
        csv << [query.campaign.domain.name, query.campaign.name, query.keyword, query.search_engine.engine, query.query_result.position, query.query_result.url, query.query_result.previous_position, query.query_result.last_updated.strftime("%d-%b-%Y")]
      end
    end

  end
end    

app/controllers/queries_controller.rb
class QueriesController < ApplicationController

  require "#{Rails.root}/lib/modules/pre_crawler"
  extend PreCrawler

  before_action :set_query, only: [:show, :edit, :update, :destroy]

  # GET /queries
  # GET /queries.json
  def index
    @queries = Query.all
    respond_to do |format|
      if @queries
        format.html
        format.csv {send_data @queries.to_csv, filename: "keyword_positons_on_#{Time.now.strftime("%d-%b-%Y")}.csv" }
        format.xls { send_data @queries.to_csv(col_sep: "\t"), filename: "keyword_positons_on_#{Time.now.strftime("%d-%b-%Y")}.xls" }
      end
    end
  end

  # GET /queries/1
  # GET /queries/1.json
  def show
  end

  # GET /queries/new
  def new
    @query = Query.new
  end

  # GET /queries/1/edit
  def edit
  end

  # POST /queries
  # POST /queries.json
  def create
    @query = Query.new(query_params)

    respond_to do |format|
      if @query.save
        format.html { redirect_to @query, notice: 'Query was successfully created.' }
        format.json { render :show, status: :created, location: @query }
      else
        format.html { render :new }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /queries/1
  # PATCH/PUT /queries/1.json
  def update
    respond_to do |format|
      if @query.update(query_params)
        format.html { redirect_to @query, notice: 'Query was successfully updated.' }
        format.json { render :show, status: :ok, location: @query }
      else
        format.html { render :edit }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def add_or_update

    params = query_params
    crawler_engine = PreCrawler.select_crawler(params[:search_engine_id])
    crawler = crawler_engine[0]
    engine = crawler_engine[1]
    keywords = PreCrawler.get_keywords(params[:keyword])
    domain = PreCrawler.get_domain(params[:campaign_id])
    query_ids = get_query(keywords, params[:campaign_id], params[:search_engine_id])
    FindPositionWorker.break_keywords(crawler, domain, query_ids, engine)
    redirect_to authenticated_root_path, :flash   => { :success => "Your keywords will be finding its position very soon!!!" }
  end
  # DELETE /queries/1
  # DELETE /queries/1.json
  def destroy
    @query.destroy
    respond_to do |format|
      format.html { redirect_to queries_url, notice: 'Query was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_query
      @query = Query.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def query_params
      params.require(:query).permit(:keyword, :campaign_id, :search_engine_id)
    end


    def get_query keywords, campaign_id, search_engine_id
      query_ids = []
      keywords.each do |keyword|
        query_ids << Query.find_or_create_by(keyword: keyword.downcase.strip, campaign_id: campaign_id, search_engine_id: search_engine_id ).id
      end
      query_ids
    end


    def get_search_engine search_engine_id
      SearchEngine.find search_engine_id
    end
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/_form.html.erb
   <div class="form-group">
    <%= form_for(@query, url: get_query_path, html: {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @query.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@query.errors.count, "error") %> prohibited this query from being saved:</h2>

          <ul>
          <% @query.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row">
        <div class="form-group">
          <div class="span2">
            <%= f.label :keyword, class: "col-sm-2 control-label" %>
          </div>
          <div class="span2">
            <%= f.text_area :keyword, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="span2">
            <label class="col-sm-2 control-label">Domain</label>
          </div>
          <div class="span6">
            <%= select_tag "domain_id", options_from_collection_for_select(@domains, "id", "name"), class: "form-control",  prompt: "---Select domain---", onchange: "prepSelect(this,'#query_campaign_id', '/get_campaigns/', 'name');" %>
          </div>
        </div>
      </div>
      <br>

      <div class="row">
        <div class="span2">
          <%= f.label :campaign_id, class: "control-label" %>
        </div>
        <div class="span2">
          <%= f.select "campaign_id", options_from_collection_for_select(@campaigns, "id", "name"), class: "form-control" %>
        </div>
        <div class="form-group">          
          <div class="span2">
            <%= f.label :search_engine_id, class: "control-label" %>
          </div>
          
          <div class="span6">
            <%= f.select "search_engine_id", options_from_collection_for_select(@search_engines, "id","engine"), class: "form-control" %>
          </div>
        </div>
      </div>
      <br>

      <div class="row">
        <div class="span4 offset3">
          <%= f.submit "submit", class: "btn btn-large btn-primary" %>
        </div>
      </div>
      <br>

      </div>
    <% end %>
  </div>

app/views/queries/edit.html.erb
<h1>Editing query</h1>

<%= render 'form' %>

<%= link_to 'Show', @query %> |
<%= link_to 'Back', queries_path %>

app/views/queries/index.html.erb
<h1>Listing queries</h1>

<table id='queries' class='display'>
  <thead>
    <tr>
      <th>Keyword</th>
      <th>Campaign</th>
      <th>Search engine</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @queries.each do |query| %>
      <tr>
        <td><%= query.keyword %></td>
        <td><%= query.campaign.name %></td>
        <td><%= query.search_engine.engine %></td>
        <td><%= link_to 'Show', query %> | <%= link_to 'Edit', edit_query_path(query) %> |<%= link_to 'Destroy', query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Query', new_query_path %>

app/views/queries/new.html.erb
<h1>New query</h1>

<%= render 'form' %>

<%= link_to 'Back', queries_path %>

app/views/queries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword:</strong>
  <%= @query.keyword %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @query.campaign %>
</p>

<p>
  <strong>Search engine:</strong>
  <%= @query.search_engine %>
</p>

<%= link_to 'Edit', edit_query_path(@query) %> |
<%= link_to 'Back', queries_path %>